### ISSUE TITLE
Is there a way to prioritize by whole file name?

### ISSUE THREAD

**Issue by alefpereira** [natecraddock/zf#3]
Hello, I really like this extension by the same reasons you created it :), between the alternative it matches my workflow the best by far.

There is a case where I think `zf` could improve, I set the following file tree to illustrate it. For example, searching for `app.py` will sort `test_app.py` first. Is there a way to prioritize by whole file name in that case?

```
.
├── myownmod
│   └── custom
│       └── app.py
└── tests
    └── test_app.py
```
or
```
./myownmod/custom/app.py
./tests/test_app.py
```

![zf-search](https://i.imgur.com/fBAxwSd.png)

**Comment by natecraddock** [comment]
I see two possibilities here:

1. If the query string matches the filename _exactly_, then that item is given a score bonus and will be ranked higher in the results

2. It might be reasonable to add a bonus score always. For example

    `test_app.py` and `app.py` would both match the query `app`; however, `app.py` matches on 50% of chars, and `test_app.py` only matches on 27% of chars. So both could be given a bonus, but the bonus would be relative to the percent matched. This would be nice so you don't have to type the exact filename each time.

I will experiment with this and report back here. There is always a pretty simple workaround for now, just add "c" to the query string in this example and the correct path will match.

**Comment by alefpereira** [comment]
Thank you for a such quick and thoughtful response.

> (...)
> What happens here is that both strings rank the same, but `./tests/test_app.py` is shorter than `./myownmod/custom/app.py` so `test_app.py` sorts first.
> (...)
> I will experiment with this and report back here.  (...)

I suspected it was something like that. I appreciate the job your are doing.  I don't know much about sorting, and nothing about zig nor performance optimization, but if I could help with testing or something just ping me.

> There is always a pretty simple workaround for now, just add "c" to the query string in this example and the correct path will match. So search for "app c"

This is interesting, for sure I'm gonna try this tomorrow on my real env. Thank you!

**Comment by natecraddock** [comment]
@alefpereira sorry for the wait! I implemented both 1 and 2. You said you would be willing to test it, how is the easiest for you? If you have zig and can compile zf, just switch to the `feat-3-name-coverage-priority` branch for testing. Otherwise I can compile libzf for you to test with the telescope extension.

**Comment by natecraddock** [comment]
@alefpereira I have included this fix in the latest updates to https://github.com/natecraddock/telescope-zf-native.nvim. Let me know if that helped!
