### ISSUE TITLE
Is v0.8.0 the latest release?

### ISSUE THREAD

**Issue by p-linnane** [natecraddock/zf#33]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v0.8.0 of zf we noticed that it's not marked as the latest release on GitHub. Was hoping to get some clarification here. Thanks!

Relates to https://github.com/Homebrew/homebrew-core/pull/125709

**Comment by natecraddock** [comment]
Hi! Yes 0.8.0 is the latest release. I was planning on making the official GitHub release later today, I didn't realize that the tag would cause confusion.

Thanks for staying on top of things in homebrew!

**Comment by natecraddock** [comment]
@p-linnane I just finished the GitHub release. Sorry again for the confusion!

**Comment by p-linnane** [comment]
Thank you!
