### ISSUE TITLE
some problems that block me adopting zf

### ISSUE THREAD

**Issue by haolian9** [natecraddock/zf#37]
hi folks, thanks for making this awesome tool!
i want to use zf in my nvim plugin and here are some problems that stop me from adopting zf.
and i do know zf aims to be simple and can be use as a library, but i still think it's worth to put them here.

a) able to read from a file
nvim does not support `ls | zf` without using a shell
https://github.com/neovim/neovim/issues/23141

b) able to save output as a file
since zf itself uses stdout or stderr to show its tui, i'd like to get user's
choice from a known file. you may say 'why not use ls | zf > file`, that
invokes a shell, i do want to avoid invoking that.

c) settable keybinds to choose the item, and output the triggered keybind
this is essential to my use, with it, i can know which way that user wants my
plugin to deal with the choice.
for example, `<c-o>` for editing the chose file in nvim, `<c-t>` for editing the
file in new tab, `<c-v` for editing the file in a vertical split.

d) able to set last query and use last query as a placeholder
maybe it's possible to do without changing the implementation: feeding last query in zf's stdin when its tui is ready.
even it's doable by that way, we has no way to support this `placeholder` feature at now.
this `placeholder` feature is just like how [the HTML tag `<input>` works](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#placeholder):
once user input something new, the placeholder will be erased.

**Comment by natecraddock** [comment]
Hi @haolian9!

You have some interesting suggestions here. I am not immediately against any of them, though I am hesitant to add unneeded complexity to zf. Before discussing the individual points in your request, I would appreciate some clarification

> i want to use zf in my nvim plugin and here are some problems that stop me from adopting zf.

Do you mind if I ask what this plugin is? It sounds like you want to use zf to filter something, are you building your own fuzzy finder? The more information you give the more I think I'll be able to help!

Just in case you didn't see it, there is already [telescope-zf-native.nvim](https://github.com/natecraddock/telescope-zf-native.nvim) that integrates zf into the telescope fuzzy finder.

**Comment by haolian9** [comment]
yeah, i rolled my own one, you can find it [here](https://github.com/haolian9/fond.nvim), and it's [core implementation](https://github.com/haolian9/fond.nvim/blob/master/lua/fond/fzf.lua#L79).
i finished it half year ago, and it remains unknown to people which made me hesitate to mention it when i opened this issue. it's based on a fzf fork which implemented this so-called placeholder feature. and as time passes, it gets harder for me to keep my fzf fork up to date with the upstream, so i want a replacement, and hopping it's simplier (no heavy feature like preview, http api) and maintainable (by myself, if i have to implement some features by me)

**Comment by haolian9** [comment]
i used to use telescope, but found it too complex, so i finally made my own one based on nvim's terminal. and later  [azy.nvim](https://github.com/vigoux/azy.nvim) emerged which uses a similar approach as telescope-zf-native.nvim uses: nvim's floatwin for the ui, ffi to utilize fzy.so.
and i played with azy, but i still prefer the terminal approach.
