### ISSUE TITLE
breaks on control sequences in folder/file name

### ISSUE THREAD

**Issue by matu3ba** [natecraddock/zf#4]
Reproduce with:
```sh
git clone https://github.com/matu3ba/chepa/tree/cdbc5cc3574aa38f7604a77d57745f854d8ef783
cd chepa
zig build tfgen
cd test_folders && rm -fr base_perf && rm -fr control_sequences
cd control_sequences
fd -t f | zf
```
output:
```txt
>
./f_
./f_
./f_
./f_
./f_
./f_
./f_
./f_
./f_
./f_
```

Picture related
![breaks_on_control_sequences](https://user-images.githubusercontent.com/13089667/155135581-6b9fb649-228c-404f-aac5-1039da240e5d.png)

**Comment by matu3ba** [comment]
Either 1. check this with a perf/complexity cost or 2. document the behavior

**Comment by natecraddock** [comment]
Hi! Sorry I haven't had the time to look into this yet. It's on my todo list for this week, thank you for the reminder!

**Comment by natecraddock** [comment]
As I mentioned in the other issue, sorry for not getting to this for nearly a year! I appreciate your checking that zf handles crazy cases.

I think this is a case where zf just won't be bothered to handle the unusual excape characters. I don't think many people would even consider this to be a use case. I'll document this and then close the issue.

**Comment by natecraddock** [comment]
Actually, I think this issue serves as good enough documentation. If many people come asking, I'll update the readme.
