### ISSUE TITLE
Usable as C library?

### ISSUE THREAD

**Issue by mizlan** [natecraddock/zf#43]
The documentation states this is usable as a C library, but it says TODO in that respective section. Can I use this as a C library (through FFI)?

**Comment by natecraddock** [comment]
Hey @mizlan sorry for the misunderstanding there. I do maintain a C library interface for zf, but the docs are a TODO. Thank you for the reminder, I'll try to update those soon.

The C interface is in this file: https://github.com/natecraddock/zf/blob/master/src/clib.zig

I maintain https://github.com/natecraddock/telescope-zf-native.nvim that uses zf for a neovim telescope fuzzy finder sorter. You can look at that repo for some inspiration.

If you need more details please let me know!
