### ISSUE TITLE
zf install from AUR fails 

### ISSUE THREAD

**Issue by primeapple** [natecraddock/zf#62]
Installing zf from the aur fails with the message

```
==> Starting build()...
/home/me/.cache/yay/zf/src/zf-0.9.0/build.zig.zon:1:2: error: missing top-level 'paths' field
.{
 ^
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: zf-exit status 4
checking dependencies...
```

May be related to https://github.com/natecraddock/zf/pull/61

**Comment by natecraddock** [comment]
Sorry I've been busy! The latest release of zf is incompatible with zig 0.12.0. I'll make a new release

**Comment by natecraddock** [comment]
I eventually intend to switch to https://github.com/rockorager/libvaxis for the UI and potentially drop ziglyph/zg. So hopefully this is just a quick fix because I didn't look too closely at the posix stuff. Thank you for catching this and fixing things! Sorry again for the delay

**Comment by natecraddock** [comment]
Hey @primeapple I finally had time to fix my Arch Linux install. This should be good to go with Zig 0.12.1

https://aur.archlinux.org/packages/zf

**Comment by natecraddock** [comment]
Let me know if you have any other troubles
