### ISSUE TITLE
Update to libvaxis 0.5.1

### ISSUE THREAD

**Issue by mitchellh** [natecraddock/zf#68]
This fixes a dependency issue where an upstream repository moved. (zg)

Thank you!

**Comment by natecraddock** [comment]
I saw the discussion in the ghostty discord about zg moving and forgot that ghostty uses zf. I'll fix this asap, thanks for the heads up!

**Comment by natecraddock** [comment]
Alright, using libvaxis 0.5.1 now! https://github.com/natecraddock/zf/releases/tag/0.10.2

**Comment by mitchellh** [comment]
Thank you!
